name: beelore
favicon: null
layout_spectrum: 0.4759852506686002
typography_spectrum: 0.13406747207045555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.29984908690676093
  lightness: 0.06562863802537322
  saturation: 0.3562762828078121
  rhythmicContrast: 0.425656410632655
purpose: []
